[options]
grid = "staggered2D.BasicStaggered2D"
pool = "n_sink.NSink"
model = "stokes_2D_mg.IncompressibleStokes2DMG"
checkpoint_interval = 5
framedump_interval = 1
seed = 42
load_checkpoint = true

[parameters]
# Initial time step
dt_initial = 1e11

# Time integration options
max_iterations=20

# Grid options
xsize = 100000 # Hortizontal size, m
ysize = 100000 # Vertical size, m
nx = 501       # Horizontal resolution
ny = 601       # Vertical resolution
gy = 10.0      # Vertical gravity, m/s^2

# Marker options
# Boundary conditions: no slip=1, free slip=-1
BC = -1
cfl_dispmax = 0.5
L = 5e3

# Marker options
nmpcx = 4 # Number of markers per cell in x direction
nmpcy = 4 # Number of markers per cell in y direction

# Inclusion options
n_sediments = 7 # Number of sediment inclusions
r = 6000 # Inclusion radius, m
r_dev = 0.25 # Deviation of inclusion radius, fraction of r

# Material options
eta_plume = 1e26
rho_plume = 3300.0
eta_mantle = 1e18
rho_mantle = 3200.0
p_ref = 1e9  # Reference pressure at (i, j) = (1, 1)

# Viscosity scaling
eta_scaling = true
eta_cycle_interval = 25
eta_ncycles = 4