[options]
grid = "staggered2D.BasicStaggered2D"
pool = "inclusion2D.RectangularInclusion"
model = "advection_2D.ConstantVelocityAdvection2D"
checkpoint_interval = 100000
framedump_interval = 20

[parameters]
# Initial time step
dt_initial = 69.420

# Time integration options
max_iterations=800

# Grid options
xsize = 100000 # Hortizontal size, m
ysize = 100000 # Vertical size, m
nx = 101       # Horizontal resolution
ny = 101       # Vertical resolution
gy = 10.0      # Vertical gravity, m/s^2

# Marker options
# Boundary conditions: no slip=1, free slip=-1
BC = -1

# Marker options
nmpcx = 4 # Number of markers per cell in x direction
nmpcy = 4 # Number of markers per cell in y direction

# Inclusion options
h = 20000 # Inclusion height, m
w = 50000 # Inclusion radius, m

L = 5000

# Material options
eta_plume = 1e18
rho_plume = 3200.0
eta_mantle = 1e19
rho_mantle = 3300.0